.conform.yaml
.github/workflows/test.yml
README.md

chore: add namechange in readme

---

Containerfile

chore: add correct version in containerfile

---

.github/workflows/test.yml
.gitignore
Containerfile
development/codequality.sh
pom.xml
renovate.json

feat: add mvn support

---

src/main/java/se/digg/eudiw/config/EudiwConfig.java
src/main/java/se/digg/eudiw/controllers/MetadataController.java
src/main/java/se/digg/eudiw/controllers/PreAuthController.java
src/main/java/se/digg/eudiw/service/OpenIdFederationServiceImpl.java
src/main/resources/application-dev.yaml

chore: remove hard coded urls

---

pom.xml

chore: upgrade nimbus dependencies

---

src/main/java/se/digg/eudiw/controllers/MetadataController.java

feat: add mdl eu.europa.ec.eudi.pid_mdoc - work in progress

---

src/main/java/se/digg/eudiw/controllers/MetadataController.java

chore: add missing mdl metadata

---

src/main/java/se/digg/eudiw/controllers/CredentialController.java
src/main/java/se/digg/eudiw/credentialissuer/model/CredentialResponse.java

chore: correct credential response exkl nonce

---

data-types/src/main/java/se/digg/wallet/datatypes/sdjwt/data/SdJwt.java
src/main/java/se/digg/eudiw/controllers/CredentialController.java
src/main/java/se/digg/eudiw/credentialissuer/model/CredentialParam.java

chore: correct typ in jwt header when sd jwt vc

---

pom.xml

chore: fix dependency issue

---

src/main/java/se/digg/eudiw/controllers/CredentialController.java

chore: fix another proof binding work-around

---

src/main/java/se/digg/eudiw/config/OAuth2ServerConfig.java

feat: add par metadata in well-known

---

src/main/java/se/digg/eudiw/controllers/MetadataController.java

chore: add code_key supported in metadata

---

src/main/java/se/digg/eudiw/controllers/MetadataController.java

chore: add cwt proof metadata

---

src/main/java/se/digg/eudiw/service/CredentialIssuerServiceImpl.java

chore: change encoding of mso mdoc credential to base64 url encoded

---

src/main/java/se/digg/eudiw/controllers/PidCredentialOfferFormController.java
src/main/java/se/digg/eudiw/model/credentialissuer/AuthorizationCodeGrant.java
src/main/java/se/digg/eudiw/util/IssuerStateBuilder.java
src/main/resources/application-dev.yaml

feat: add issuer state in auth code credential offer

---

src/main/java/se/digg/eudiw/config/ValKeyConfig.java
src/main/resources/static/index.html
src/main/resources/templates/pid-credential-offer.html
src/main/resources/templates/pid-pre-auth-credential-offer.html

chore: html fixes and a fix in the proof work around

---

src/main/java/se/digg/eudiw/service/CredentialIssuerServiceImpl.java

chore: fix birth date bug in credential

---

src/main/resources/static/style/digg.css
src/main/resources/templates/index.html
src/main/resources/templates/layout.html

chore: add funded by eu logo to site and some text fixes

---

src/main/java/se/digg/eudiw/service/CredentialOfferServiceImpl.java

chore: add work-around for android ref impl wallet app

---

src/main/java/se/digg/eudiw/authorization/CustomRedirectUriValidator.java
src/main/java/se/digg/eudiw/config/OAuth2ServerConfig.java

feat: disable redirect uri verification

---

src/main/java/se/digg/eudiw/config/OAuth2ServerConfig.java

feat: add par metadata

---

src/main/java/se/digg/eudiw/authorization/OidFederatedRegisteredClientRepository.java

feat: skip consent page for pid issuance

---

src/main/java/se/digg/eudiw/config/RestClientConfig.java

feat: disable ewc itb automatic cookie management for rest client

---

pom.xml
src/main/java/se/digg/eudiw/model/credentialissuer/CredentialFormatEnum.java
src/main/java/se/digg/eudiw/service/MetadataServiceImpl.java

- use new version of openid-federation-metadata
- new structure of Credential Configuration regarding claims
- format "vc+sd-jwt" renamed to "dc+sd-jwt"
Fixes #(issue)

feat: update to follow Draft 15 of OID4VCI

---

src/main/java/se/digg/eudiw/model/credentialissuer/Credential.java
src/main/java/se/digg/eudiw/model/credentialissuer/CredentialResponse.java

feat: add support for list of credentials in credential end-point

---

src/main/java/se/digg/eudiw/controllers/EwcItbController.java
src/main/java/se/digg/eudiw/service/MetadataServiceImpl.java

feat: update vct and type to latest specification

---

src/main/java/se/digg/eudiw/service/CredentialIssuerServiceImpl.java
src/main/java/se/digg/eudiw/service/MetadataServiceImpl.java

feat: add optional personal_administrative_number to sdjwt pid

---

.github/workflows/openssfscorecard.yml

ci: use openssf-scorecard v1
